# -*- coding: utf-8 -*-
"""Medical SLM Chunking Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/115HhoQAOzo-39GzrBjxu7d_fhvmXNWdz

# Medical SLM Chunking Pipeline

This notebook handles serialization, chunking and metadata enrichment of `documents.csv` for our Domain-Specific Medical Small Language Model (SLM).

### Why 1 Row = 1 Chunk
Medical guidelines contain critical clinical rules (dosages, warnings, symptoms). Standard character-based chunking risks splitting a condition from its warning. Since each row in `documents.csv` is an atomic clinical guideline, 1 row = 1 chunk.
"""

# Loading Libraries
import pandas as pd
import json
from pathlib import Path

print("Libraries loaded successfully!")

# Path to raw dataset
csv_file_path = "documents.csv"

# Loading data into DataFrame
df = pd.read_csv(csv_file_path)

# Verifing counts and column structure
print(f"Total documents loaded: {len(df)}")
print("\nDataset Columns:", df.columns.tolist())

# Previewing to confirm structure
df.head(1)

# Serialization & Formatting
def format_row_to_chunk(row):

    # Front-loading key metadata into text payload so vector embeddings
    # retain care setting and target population context
    formatted_text = (
        f"**Title:** {row['title']}\n"
        f"**Topic:** {row['topic']} | **Care Setting:** {row['care_setting']} | **Population:** {row['population']}\n"
        f"**Guidance:** {row['text']}"
    )

    # Extracting clean key-value pairs for metadata filtering in database
    metadata = {
        "document_id": row['document_id'],
        "title": row['title'],
        "topic": row['topic'],
        "care_setting": row['care_setting'],
        "population": row['population'],
        "origin": row['origin'],
        "license": row['license']
    }

    return {
        "id": row['document_id'],
        "text": formatted_text,
        "metadata": metadata
    }

# Processing all 24 Medical entries
processed_chunks = []

# Iterate over each row in the dataset
for index, row in df.iterrows():
    chunk = format_row_to_chunk(row)
    processed_chunks.append(chunk)

print(f"Successfully serialized {len(processed_chunks)} medical chunks.")

# Inspecting the first formatted chunk (Chronic Disease example)
print("--- SAMPLE CHUNK 1 (Chronic Disease) ---")
print("TEXT PAYLOAD:\n", processed_chunks[0]['text'])
print("\nMETADATA:\n", json.dumps(processed_chunks[0]['metadata'], indent=2))

print("\n" + "="*50 + "\n")

# Inspecting an emergency triage chunk (Emergency example)
print("--- SAMPLE CHUNK 19 (Emergency Triage) ---")
print("TEXT PAYLOAD:\n", processed_chunks[18]['text'])
print("\nMETADATA:\n", json.dumps(processed_chunks[18]['metadata'], indent=2))

# Saveing Processed Chunks

output_file_path = "medical_chunks.json"

# Exporting to clean JSON format for vector database ingestion
with open(output_file_path, "w", encoding="utf-8") as f:
    json.dump(processed_chunks, f, indent=2)

print(f" Process Complete! Exported {len(processed_chunks)} chunks to '{output_file_path}'.")